services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - ./.env

  db:
    build:
      context: .
      dockerfile: Dockerfile.db
    container_name: db
